# Generated by Django 3.1.1 on 2020-09-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_img',
            field=models.ImageField(default='default_bg.jpg', upload_to='background_pics'),
        ),
    ]
