# Generated by Django 3.1.1 on 2020-09-11 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_credential_iv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='iv',
        ),
    ]
